package io.aegis
import java.math.*
import java.security.MessageDigest
import kotlinx.coroutines.sync.*
enum class Env{DEMO,REAL};enum class Round{UNKNOWN,WAITING,BETTING_OPEN,BETTING_CLOSED,RUNNING,CRASHED,FINISHED};enum class Panel{P1,P2};enum class Outcome{WIN,LOSS,UNKNOWN};enum class CType{STAKE,BET,CASHOUT,MULTIPLIER,ROUND,BALANCE,RESULT,UNKNOWN}
data class Box(val l:Int,val t:Int,val r:Int,val b:Int);data class Candidate(val path:List<Int>,val type:CType,val text:String?,val id:String?,val box:Box,val clickable:Boolean,val editable:Boolean,val confidence:Double,val panel:Panel?=null);data class Fingerprint(val structure:String,val labels:String);data class Profile(val pkg:String,val fingerprint:Fingerprint,val controls:Map<String,Candidate>,val validated:Boolean);data class PanelConfig(val base:BigDecimal,val factor:BigDecimal=BigDecimal.TEN,val max:BigDecimal=BigDecimal("100000"),val maxLevel:Int=10);data class Progress(val stake:BigDecimal,val level:Int=0,val losses:Int=0,val outcome:Outcome?=null)
class Progression(private val c:PanelConfig,s:Progress){var state=s.copy(stake=s.stake.setScale(2,RoundingMode.HALF_EVEN));private set;fun apply(o:Outcome):Progress{state=when(o){Outcome.WIN->Progress(c.base.setScale(2),outcome=o);Outcome.UNKNOWN->state.copy(outcome=o);Outcome.LOSS->{val n=state.stake.multiply(c.factor).setScale(2);check(n<=c.max&&state.level<c.maxLevel){"SAFETY_LIMIT"};state.copy(stake=n,level=state.level+1,losses=state.losses+1,outcome=o)}};return state}}
class EnvGuard{var env=Env.DEMO;private set;private var ack=false;private var started=false;fun select(e:Env,a:String?=null){if(e==Env.REAL){require(a=="I UNDERSTAND THE RISKS");ack=true;started=false}else{ack=false;started=false};env=e};fun start(valid:Boolean){check(valid&&(env==Env.DEMO||ack));started=true};fun restart(){started=false};fun mayAct()=env==Env.DEMO&&started||env==Env.REAL&&ack&&started}
object OutcomeResolver{fun resolve(d:Outcome?,history:Outcome?,cash:Boolean?,ended:Boolean?,accepted:Boolean?,payout:Boolean?,balanceChanged:Boolean?):Outcome{if(d!=null&&history!=null&&d!=history)return Outcome.UNKNOWN;d?.let{return it};history?.let{return it};if(cash==true)return Outcome.WIN;if(ended==true&&accepted==true&&payout==false)return Outcome.LOSS;return Outcome.UNKNOWN}}
object Mapper{private fun classify(s:String,e:Boolean)=when{e||"stake" in s||"amount" in s->CType.STAKE;"cash" in s->CType.CASHOUT;"place bet" in s||s=="bet"->CType.BET;"multiplier" in s||Regex("[0-9.]+x").containsMatchIn(s)->CType.MULTIPLIER;"round" in s||"crashed" in s||"waiting" in s->CType.ROUND;"balance" in s->CType.BALANCE;"won" in s||"lost" in s||"result" in s->CType.RESULT;else->CType.UNKNOWN};fun map(raw:List<Candidate>):List<Candidate>{val cs=raw.map{val s=listOfNotNull(it.text,it.id).joinToString(" ").lowercase();val t=classify(s,it.editable);it.copy(type=t,confidence=if(t==CType.UNKNOWN)0.2 else if(!it.id.isNullOrBlank())0.94 else 0.75)};val a=cs.filter{it.type in setOf(CType.STAKE,CType.BET,CType.CASHOUT)};if(a.size<6)return cs;val m=a.map{it.box.t}.sorted()[a.size/2];val top=a.filter{it.box.t<m};val bot=a.filter{it.box.t>=m};val req=setOf(CType.STAKE,CType.BET,CType.CASHOUT);if(top.map{it.type}.toSet()!=req||bot.map{it.type}.toSet()!=req)return cs;return cs.map{when(it){in top->it.copy(panel=Panel.P1);in bot->it.copy(panel=Panel.P2);else->it}}};fun valid(c:List<Candidate>)=Panel.entries.all{p->setOf(CType.STAKE,CType.BET,CType.CASHOUT).all{t->c.any{it.panel==p&&it.type==t&&it.confidence>=.6}}}&&c.any{it.type==CType.ROUND}&&c.any{it.type==CType.MULTIPLIER};fun fingerprint(cs:List<Candidate>)=Fingerprint(hash(cs.joinToString{"${it.path}:${it.clickable}"}),hash(cs.mapNotNull{it.text}.sorted().joinToString()));private fun hash(s:String)=MessageDigest.getInstance("SHA-256").digest(s.toByteArray()).take(12).joinToString(""){"%02x".format(it)}}
class ActionLocks{private val locks=Panel.entries.associateWith{Mutex()};private val sent=mutableSetOf<Pair<String,Panel>>();suspend fun submit(round:String,p:Panel,preflight:()->Boolean,act:suspend()->Boolean)=locks.getValue(p).withLock{if(!preflight()||!sent.add(round to p))false else if(act())true else{sent.remove(round to p);false}}}
class Watchdog(private val stale:Long=15000){fun paused(now:Long,last:Long,connected:Boolean,contradictory:Boolean,failures:Int,max:Int)=!connected||contradictory||failures>=max||now-last>stale}
